use convert_case::{Case, Casing};

use crate::strings::types::*;

/// Generate Swift source code from a parsed locale file.
///
/// Produces a single file with:
/// - A top-level `Strings` enum with nested structs per root group
/// - Each struct has typed accessors (computed properties for plain strings,
///   methods for templates/plurals/gendered)
/// - A `StringResolver` protocol the runtime must implement
pub fn generate(file: &LocaleFile) -> String {
    let mut out = String::new();

    out.push_str("// Auto-generated by forge-cli. Do not edit.\n\n");
    out.push_str("import Foundation\n\n");

    // Resolver protocol — the runtime provides this
    out.push_str("/// Protocol that the Forge runtime implements to resolve strings\n");
    out.push_str("/// from the current locale, falling back to defaults.\n");
    out.push_str("public protocol StringResolver {\n");
    out.push_str("    func string(_ key: String) -> String\n");
    out.push_str("    func template(_ key: String, params: [String: String]) -> String\n");
    out.push_str("    func plural(_ key: String, count: Int, params: [String: String]) -> String\n");
    out.push_str("    func gendered(_ key: String, gender: Gender, params: [String: String]) -> String\n");
    out.push_str("    func list(_ key: String) -> [String]\n");
    out.push_str("    func reference(_ key: String) -> String\n");
    out.push_str("    func nested(_ prefix: String) -> StringResolver\n");
    out.push_str("}\n\n");

    out.push_str("public enum Gender {\n");
    out.push_str("    case male, female, other\n");
    out.push_str("}\n\n");

    // Top-level Strings enum — namespace for all view string structs
    out.push_str("public enum Strings {\n");

    for entry in &file.root.entries {
        if let Value::Group(group) = &entry.value {
            let struct_name = entry.key.to_case(Case::Pascal);
            emit_struct(&mut out, &struct_name, &entry.key, group, 1);
        }
    }

    out.push_str("}\n");

    out
}

fn emit_struct(out: &mut String, name: &str, key_prefix: &str, group: &Group, indent: usize) {
    let pad = "    ".repeat(indent);

    out.push_str(&format!("\n{pad}public struct {name} {{\n"));
    out.push_str(&format!("{pad}    let resolver: StringResolver\n\n"));

    for entry in &group.entries {
        emit_accessor(out, entry, key_prefix, indent + 1);
    }

    out.push_str(&format!("{pad}}}\n"));
}

fn emit_accessor(out: &mut String, entry: &Entry, key_prefix: &str, indent: usize) {
    let pad = "    ".repeat(indent);
    let key = &entry.key;
    let full_key = format!("{key_prefix}.{key}");

    match &entry.value {
        Value::Plain(_) => {
            out.push_str(&format!(
                "{pad}public var {}: String {{ resolver.string(\"{}\") }}\n",
                safe_name(key),
                full_key
            ));
        }

        Value::Template(t) => {
            let mut sig_params = Vec::new();
            let mut dict_entries = Vec::new();
            if t.has_n {
                sig_params.push("_ n: Int".to_string());
                dict_entries.push("\"n\": String(n)".to_string());
            }
            for p in &t.params {
                sig_params.push(format!("{p}: String"));
                dict_entries.push(format!("\"{p}\": {p}"));
            }
            out.push_str(&format!(
                "{pad}public func {}({}) -> String {{\n",
                safe_name(key),
                sig_params.join(", ")
            ));
            out.push_str(&format!(
                "{pad}    resolver.template(\"{}\", params: [{}])\n",
                full_key,
                dict_entries.join(", ")
            ));
            out.push_str(&format!("{pad}}}\n"));
        }

        Value::Plural(p) => {
            let extra_params = p.all_params();
            let mut sig_params = vec!["_ n: Int".to_string()];
            let mut dict_entries = vec!["\"n\": String(n)".to_string()];
            for ep in &extra_params {
                sig_params.push(format!("{ep}: String"));
                dict_entries.push(format!("\"{ep}\": {ep}"));
            }
            out.push_str(&format!(
                "{pad}public func {}({}) -> String {{\n",
                safe_name(key),
                sig_params.join(", ")
            ));
            out.push_str(&format!(
                "{pad}    resolver.plural(\"{}\", count: n, params: [{}])\n",
                full_key,
                dict_entries.join(", ")
            ));
            out.push_str(&format!("{pad}}}\n"));
        }

        Value::Gendered(g) => {
            let extra_params = g.all_params();
            let mut sig_params = Vec::new();
            let mut dict_entries = Vec::new();
            if g.has_n() {
                sig_params.push("_ n: Int".to_string());
                dict_entries.push("\"n\": String(n)".to_string());
            }
            sig_params.push("gender: Gender".to_string());
            for ep in &extra_params {
                sig_params.push(format!("{ep}: String"));
                dict_entries.push(format!("\"{ep}\": {ep}"));
            }
            out.push_str(&format!(
                "{pad}public func {}({}) -> String {{\n",
                safe_name(key),
                sig_params.join(", ")
            ));
            out.push_str(&format!(
                "{pad}    resolver.gendered(\"{}\", gender: gender, params: [{}])\n",
                full_key,
                dict_entries.join(", ")
            ));
            out.push_str(&format!("{pad}}}\n"));
        }

        Value::List(list) => {
            // Check if it's a list of groups (struct list) or plain strings
            let has_groups = list.items.iter().any(|i| matches!(i, Value::Group(_)));
            if has_groups {
                // For lists of structs, generate an item struct + computed array
                let item_name = format!("{}Item", key.to_case(Case::Pascal));
                if let Some(Value::Group(first_group)) = list.items.first() {
                    emit_struct(out, &item_name, &format!("{full_key}.0"), first_group, indent);
                }
                out.push_str(&format!(
                    "\n{pad}public var {}: [{}] {{\n",
                    safe_name(key),
                    item_name
                ));
                out.push_str(&format!(
                    "{pad}    (0..<{}).map {{ {item_name}(resolver: resolver.nested(\"{full_key}.\\($0)\")) }}\n",
                    list.items.len()
                ));
                out.push_str(&format!("{pad}}}\n"));
            } else {
                out.push_str(&format!(
                    "{pad}public var {}: [String] {{ resolver.list(\"{}\") }}\n",
                    safe_name(key),
                    full_key
                ));
            }
        }

        Value::Group(group) => {
            let struct_name = key.to_case(Case::Pascal);
            emit_struct(out, &struct_name, &full_key, group, indent);
            out.push_str(&format!(
                "\n{pad}public var {}: {} {{\n",
                safe_name(key),
                struct_name
            ));
            out.push_str(&format!(
                "{pad}    {}(resolver: resolver.nested(\"{}\"))\n",
                struct_name, full_key
            ));
            out.push_str(&format!("{pad}}}\n"));
        }

        Value::Reference(_) => {
            out.push_str(&format!(
                "{pad}public var {}: String {{ resolver.reference(\"{}\") }}\n",
                safe_name(key),
                full_key
            ));
        }
    }
}

/// Escape Swift reserved words.
fn safe_name(name: &str) -> &str {
    match name {
        "class" | "struct" | "enum" | "func" | "var" | "let" | "import" | "return" | "switch"
        | "case" | "default" | "break" | "continue" | "for" | "while" | "if" | "else"
        | "in" | "is" | "as" | "true" | "false" | "nil" | "self" | "Self" | "super"
        | "type" | "protocol" => name, // TODO: backtick-escape these
        _ => name,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::strings::parser;

    fn parse_json(json: &str) -> LocaleFile {
        let value: serde_json::Value = serde_json::from_str(json).unwrap();
        let map = value.as_object().unwrap();
        LocaleFile {
            locale: "en".into(),
            root: parser::parse_group(map),
        }
    }

    #[test]
    fn test_plain_string() {
        let file = parse_json(r#"{ "settings": { "title": "Settings" } }"#);
        let output = generate(&file);
        assert!(output.contains("public var title: String { resolver.string(\"settings.title\") }"));
    }

    #[test]
    fn test_template() {
        let file = parse_json(r#"{ "home": { "greeting": "Hello, {name}" } }"#);
        let output = generate(&file);
        assert!(output.contains("public func greeting(name: String) -> String {"));
        assert!(output.contains("resolver.template(\"home.greeting\", params: [\"name\": name])"));
    }

    #[test]
    fn test_template_with_n() {
        let file = parse_json(r#"{ "home": { "followers": "{n} followers" } }"#);
        let output = generate(&file);
        assert!(output.contains("public func followers(_ n: Int) -> String {"));
        assert!(output.contains("\"n\": String(n)"));
    }

    #[test]
    fn test_template_n_plus_params() {
        let file = parse_json(r#"{ "home": { "filesIn": "{n} files in {folder}" } }"#);
        let output = generate(&file);
        assert!(output.contains("public func filesIn(_ n: Int, folder: String) -> String {"));
    }

    #[test]
    fn test_plural() {
        let file = parse_json(
            r#"{ "home": { "itemCount(plural)": { "one": "{n} item", "other": "{n} items" } } }"#,
        );
        let output = generate(&file);
        assert!(output.contains("public func itemCount(_ n: Int) -> String {"));
        assert!(output.contains("resolver.plural(\"home.itemCount\", count: n"));
    }

    #[test]
    fn test_plural_with_extra_params() {
        let file = parse_json(
            r#"{ "home": { "fileCount(plural)": { "one": "{n} file in {folder}", "other": "{n} files in {folder}" } } }"#,
        );
        let output = generate(&file);
        assert!(output.contains("public func fileCount(_ n: Int, folder: String) -> String {"));
    }

    #[test]
    fn test_gendered() {
        let file = parse_json(
            r#"{ "profile": { "header(gender)": { "male": "his", "female": "her", "other": "their" } } }"#,
        );
        let output = generate(&file);
        assert!(output.contains("public func header(gender: Gender) -> String {"));
    }

    #[test]
    fn test_nested_group() {
        let file = parse_json(
            r#"{ "settings": { "profile": { "name": "Name", "bio": "Bio" } } }"#,
        );
        let output = generate(&file);
        assert!(output.contains("public struct Profile {"));
        assert!(output.contains("public var profile: Profile {"));
    }

    #[test]
    fn test_string_list() {
        let file = parse_json(r#"{ "onboarding": { "steps": ["First", "Second"] } }"#);
        let output = generate(&file);
        assert!(output.contains("public var steps: [String] { resolver.list(\"onboarding.steps\") }"));
    }

    #[test]
    fn test_reference() {
        let file = parse_json(r#"{ "common": { "save": "@:shared.save" } }"#);
        let output = generate(&file);
        assert!(output.contains("resolver.reference(\"common.save\")"));
    }

    #[test]
    fn test_struct_list() {
        let file = parse_json(
            r#"{ "onboarding": { "steps": [{ "title": "Welcome", "body": "Hi" }, { "title": "Done", "body": "Bye" }] } }"#,
        );
        let output = generate(&file);
        assert!(output.contains("public struct StepsItem {"));
        assert!(output.contains("public var steps: [StepsItem]"));
    }
}
