import CoreGraphics
import Foundation

// MARK: - Shape Protocol

/// A closed path constructor. Given a bounding rect, produces a closed Path.
/// Concrete shapes are value types with inspectable parameters.
///
/// `AnyShape` (generated by `@Erased`) provides type erasure with
/// Equatable + Lerpable support through the box pattern.
@Erased
public protocol Shape: Equatable, Lerpable {
    func path(in rect: Rect) -> Path
    func vertices(in rect: Rect) -> [Point]
}

extension AnyShape: Shape {}

public extension Shape {
    var erased: AnyShape { AnyShape(self) }

    func vertices(in rect: Rect) -> [Point] {
        ShapeUtils.extractVertices(from: path(in: rect))
    }
}

// MARK: - Static factories (enables `.capsule()` dot syntax in generic contexts)

public extension Shape where Self == RectShape {
    static func rect() -> RectShape { RectShape() }
}
public extension Shape where Self == RoundedModifiedShape {
    static func roundedRect(radius: Double, smooth: Double = 0.6) -> RoundedModifiedShape {
        RoundedModifiedShape(base: RectShape().erased, radii: [radius], smooth: smooth)
    }
}
public extension Shape where Self == EllipseShape {
    static func ellipse() -> EllipseShape { EllipseShape() }
}
public extension Shape where Self == CircleShape {
    static func circle() -> CircleShape { CircleShape() }
}
public extension Shape where Self == CapsuleShape {
    static func capsule() -> CapsuleShape { CapsuleShape() }
}
public extension Shape where Self == RegularPolygon {
    static func regular(sides: Int, rotation: Double = -.pi / 2) -> RegularPolygon { RegularPolygon(sides: sides, rotation: rotation) }
}
public extension Shape where Self == StarShape {
    static func star(points: Int, innerRadius: Double = 0.4, rotation: Double = -.pi / 2) -> StarShape { StarShape(points: points, innerRadius: innerRadius, rotation: rotation) }
}
public extension Shape where Self == PolygonShape {
    static func polygon(_ points: [Point]) -> PolygonShape { PolygonShape(points: points) }
}

// MARK: - Concrete Shapes

public struct RectShape: Shape, Equatable, Lerpable {
    public init() {}
    public func path(in rect: Rect) -> Path {
        var p = Path(); p.addRect(rect); return p
    }
    public func vertices(in rect: Rect) -> [Point] {
        [Point(rect.x, rect.y), Point(rect.right, rect.y),
         Point(rect.right, rect.bottom), Point(rect.x, rect.bottom)]
    }
    public func lerp(to other: RectShape, t: Double) -> RectShape { self }
}

public struct EllipseShape: Shape, Equatable, Lerpable {
    public init() {}
    public func path(in rect: Rect) -> Path {
        var p = Path(); p.addEllipse(in: rect); return p
    }
    public func lerp(to other: EllipseShape, t: Double) -> EllipseShape { self }
}

public struct CircleShape: Shape, Equatable, Lerpable {
    public init() {}
    public func path(in rect: Rect) -> Path {
        let side = min(rect.width, rect.height)
        let centered = Rect(x: rect.midX - side / 2, y: rect.midY - side / 2, width: side, height: side)
        var p = Path(); p.addEllipse(in: centered); return p
    }
    public func lerp(to other: CircleShape, t: Double) -> CircleShape { self }
}

public struct CapsuleShape: Shape, Equatable, Lerpable {
    public init() {}
    public func path(in rect: Rect) -> Path {
        let radius = min(rect.width, rect.height) / 2
        var p = Path(); p.addRoundedRect(rect, cornerWidth: radius, cornerHeight: radius); return p
    }
    public func lerp(to other: CapsuleShape, t: Double) -> CapsuleShape { self }
}

@Init @Copy @Lerp
public struct RegularPolygon: Shape, Equatable {
    @Snap public var sides: Int
    public var rotation: Double = -.pi / 2

    public func path(in rect: Rect) -> Path {
        let verts = vertices(in: rect)
        var p = Path()
        for (i, pt) in verts.enumerated() {
            if i == 0 { p.move(to: pt) } else { p.line(to: pt) }
        }
        p.close(); return p
    }
    public func vertices(in rect: Rect) -> [Point] {
        let center = rect.center; let r = rect.shortestSide / 2
        return (0..<sides).map { i in
            let angle = rotation + (2 * .pi * Double(i) / Double(sides))
            return Point(center.x + cos(angle) * r, center.y + sin(angle) * r)
        }
    }
}

@Init @Copy @Lerp
public struct StarShape: Shape, Equatable {
    @Snap public var points: Int
    public var innerRadius: Double = 0.4
    public var rotation: Double = -.pi / 2

    public func path(in rect: Rect) -> Path {
        let verts = vertices(in: rect)
        var p = Path()
        for (i, pt) in verts.enumerated() {
            if i == 0 { p.move(to: pt) } else { p.line(to: pt) }
        }
        p.close(); return p
    }
    public func vertices(in rect: Rect) -> [Point] {
        let center = rect.center; let outerR = rect.shortestSide / 2
        let innerR = outerR * innerRadius; let total = points * 2
        return (0..<total).map { i in
            let angle = rotation + (2 * .pi * Double(i) / Double(total))
            let r: Double = i.isMultiple(of: 2) ? outerR : innerR
            return Point(center.x + cos(angle) * r, center.y + sin(angle) * r)
        }
    }
}

public struct PolygonShape: Shape, Equatable, Lerpable {
    public var points: [Point]
    public init(points: [Point]) { self.points = points }
    public func path(in rect: Rect) -> Path {
        let mapped = points.map { Point(rect.x + $0.x * rect.width, rect.y + $0.y * rect.height) }
        var p = Path()
        for (i, pt) in mapped.enumerated() {
            if i == 0 { p.move(to: pt) } else { p.line(to: pt) }
        }
        p.close(); return p
    }
    public func vertices(in rect: Rect) -> [Point] {
        points.map { Point(rect.x + $0.x * rect.width, rect.y + $0.y * rect.height) }
    }
    public func lerp(to other: PolygonShape, t: Double) -> PolygonShape {
        let maxCount = max(points.count, other.points.count)
        var result: [Point] = []
        for i in 0..<maxCount {
            let a = points[min(i, points.count - 1)]
            let b = other.points[min(i, other.points.count - 1)]
            result.append(a.lerp(to: b, t: t))
        }
        return PolygonShape(points: result)
    }
}

// MARK: - Modifier Shapes

@Init @Copy @Lerp
public struct ScaledShape: Shape, Equatable {
    public var base: AnyShape
    public var sx: Double
    public var sy: Double
    public func path(in rect: Rect) -> Path {
        let p = base.path(in: rect); let center = rect.center
        let t = CGAffineTransform.identity
            .translatedBy(x: center.x, y: center.y)
            .scaledBy(x: sx, y: sy)
            .translatedBy(x: -center.x, y: -center.y)
        return p.transformed(t)
    }
}

@Init @Copy @Lerp
public struct RotatedShape: Shape, Equatable {
    public var base: AnyShape
    public var radians: Double
    public func path(in rect: Rect) -> Path {
        let p = base.path(in: rect); let center = rect.center
        let t = CGAffineTransform.identity
            .translatedBy(x: center.x, y: center.y)
            .rotated(by: radians)
            .translatedBy(x: -center.x, y: -center.y)
        return p.transformed(t)
    }
}

@Init @Copy @Lerp
public struct TranslatedShape: Shape, Equatable {
    public var base: AnyShape
    public var dx: Double
    public var dy: Double
    public func path(in rect: Rect) -> Path {
        base.path(in: rect).transformed(CGAffineTransform(translationX: dx, y: dy))
    }
}

@Init @Copy @Lerp
public struct InsetShape: Shape, Equatable {
    public var base: AnyShape
    public var amount: Double
    public func path(in rect: Rect) -> Path { base.path(in: rect.inset(by: amount)) }
}

@Init @Copy @Lerp
public struct RoundedModifiedShape: Shape, Equatable {
    public var base: AnyShape
    @Snap public var radii: [Double]
    public var smooth: Double
    public func path(in rect: Rect) -> Path {
        let verts = base.vertices(in: rect)
        guard verts.count >= 3 else { return base.path(in: rect) }
        return ShapeUtils.roundVertices(verts, radii: radii, smooth: smooth)
    }
    public func vertices(in rect: Rect) -> [Point] { base.vertices(in: rect) }
}

@Init @Copy @Lerp
public struct ChamferedShape: Shape, Equatable {
    public var base: AnyShape
    public var size: Double
    public func path(in rect: Rect) -> Path {
        let verts = base.vertices(in: rect)
        guard verts.count >= 3 else { return base.path(in: rect) }
        return ShapeUtils.chamferVertices(verts, size: size)
    }
    public func vertices(in rect: Rect) -> [Point] { base.vertices(in: rect) }
}

// MARK: - Boolean Ops

@available(iOS 16.0, macOS 13.0, *)
@Init @Copy @Lerp
public struct UnionShape: Shape, Equatable {
    public var a: AnyShape
    public var b: AnyShape
    public func path(in rect: Rect) -> Path { a.path(in: rect).union(b.path(in: rect)) }
}

@available(iOS 16.0, macOS 13.0, *)
@Init @Copy @Lerp
public struct IntersectionShape: Shape, Equatable {
    public var a: AnyShape
    public var b: AnyShape
    public func path(in rect: Rect) -> Path { a.path(in: rect).intersection(b.path(in: rect)) }
}

@available(iOS 16.0, macOS 13.0, *)
@Init @Copy @Lerp
public struct SubtractionShape: Shape, Equatable {
    public var a: AnyShape
    public var b: AnyShape
    public func path(in rect: Rect) -> Path { a.path(in: rect).subtracting(b.path(in: rect)) }
}

@available(iOS 16.0, macOS 13.0, *)
@Init @Copy @Lerp
public struct SymmetricDifferenceShape: Shape, Equatable {
    public var a: AnyShape
    public var b: AnyShape
    public func path(in rect: Rect) -> Path { a.path(in: rect).symmetricDifference(b.path(in: rect)) }
}

// MARK: - CustomShape (closure escape hatch)

public struct CustomShape: Shape, Equatable, Lerpable {
    public var id: String?
    public let factory: (Rect) -> Path
    public let verticesFactory: ((Rect) -> [Point])?

    public init(id: String? = nil, _ factory: @escaping (Rect) -> Path, vertices: ((Rect) -> [Point])? = nil) {
        self.id = id; self.factory = factory; self.verticesFactory = vertices
    }

    public func path(in rect: Rect) -> Path { factory(rect) }
    public func vertices(in rect: Rect) -> [Point] {
        verticesFactory?(rect) ?? ShapeUtils.extractVertices(from: path(in: rect))
    }

    public static func ==(lhs: CustomShape, rhs: CustomShape) -> Bool {
        guard let lid = lhs.id, let rid = rhs.id else { return false }
        return lid == rid
    }
    public func lerp(to other: CustomShape, t: Double) -> CustomShape {
        t < 0.5 ? self : other
    }
}

// MARK: - Shape Modifiers (extension on protocol)

public extension Shape {
    func scaled(_ sx: Double, _ sy: Double? = nil) -> AnyShape {
        ScaledShape(base: self.erased, sx: sx, sy: sy ?? sx).erased
    }
    func rotated(_ radians: Double) -> AnyShape {
        RotatedShape(base: self.erased, radians: radians).erased
    }
    func translated(_ dx: Double, _ dy: Double) -> AnyShape {
        TranslatedShape(base: self.erased, dx: dx, dy: dy).erased
    }
    func inset(_ amount: Double) -> AnyShape {
        InsetShape(base: self.erased, amount: amount).erased
    }
    func outset(_ amount: Double) -> AnyShape {
        InsetShape(base: self.erased, amount: -amount).erased
    }
    func round(radii: [Double], smooth: Double = 0.6) -> AnyShape {
        RoundedModifiedShape(base: self.erased, radii: radii, smooth: smooth).erased
    }
    func round(radius: Double = 8, smooth: Double = 0.6) -> AnyShape {
        round(radii: [radius], smooth: smooth)
    }
    func chamfer(size: Double) -> AnyShape {
        ChamferedShape(base: self.erased, size: size).erased
    }
}

@available(iOS 16.0, macOS 13.0, *)
public extension Shape {
    func union(_ other: some Shape) -> AnyShape {
        UnionShape(a: self.erased, b: other.erased).erased
    }
    func intersect(_ other: some Shape) -> AnyShape {
        IntersectionShape(a: self.erased, b: other.erased).erased
    }
    func subtract(_ other: some Shape) -> AnyShape {
        SubtractionShape(a: self.erased, b: other.erased).erased
    }
    func xor(_ other: some Shape) -> AnyShape {
        SymmetricDifferenceShape(a: self.erased, b: other.erased).erased
    }
}

// MARK: - Utilities

enum ShapeUtils {
    static func extractVertices(from path: Path) -> [Point] {
        var vertices: [Point] = []
        var current = CGPoint.zero

        path.cgPath.applyWithBlock { element in
            switch element.pointee.type {
            case .moveToPoint:
                current = element.pointee.points[0]
                vertices.append(Point(current))
            case .addLineToPoint:
                current = element.pointee.points[0]
                vertices.append(Point(current))
            case .addQuadCurveToPoint:
                current = element.pointee.points[1]
            case .addCurveToPoint:
                current = element.pointee.points[2]
            case .closeSubpath:
                break
            @unknown default:
                break
            }
        }

        if let first = vertices.first, let last = vertices.last,
           abs(first.x - last.x) < 0.5 && abs(first.y - last.y) < 0.5,
           vertices.count > 1 {
            vertices.removeLast()
        }

        return vertices
    }

    static func roundVertices(_ vertices: [Point], radii: [Double], smooth: Double) -> Path {
        let n = vertices.count
        var path = Path()

        var signedArea: Double = 0
        for i in 0..<n {
            let curr = vertices[i]
            let next = vertices[(i + 1) % n]
            signedArea += (next.x - curr.x) * (next.y + curr.y)
        }
        let isClockwise = signedArea < 0

        for i in 0..<n {
            let prev = vertices[(i - 1 + n) % n]
            let curr = vertices[i]
            let next = vertices[(i + 1) % n]
            let radius = radii[i % radii.count]

            let toPrev = prev - curr
            let toNext = next - curr
            let prevLen = toPrev.length
            let nextLen = toNext.length

            guard prevLen > 0, nextLen > 0 else {
                if i == 0 { path.move(to: curr) } else { path.line(to: curr) }
                continue
            }

            if radius <= 0 {
                if i == 0 { path.move(to: curr) } else { path.line(to: curr) }
                continue
            }

            let d = toPrev.dot(toNext) / (prevLen * nextLen)
            let halfAngle = acos(min(1, max(-1, d))) / 2

            guard halfAngle > 0.001 else {
                if i == 0 { path.move(to: curr) } else { path.line(to: curr) }
                continue
            }

            let cross = toPrev.cross(toNext)
            let concave = isClockwise ? cross > 0 : cross < 0

            let baseOffset = radius / tan(halfAngle)
            let maxOffset = min(prevLen, nextLen) * 0.45
            let offset = min(baseOffset, maxOffset)
            let effectiveRadius = offset * tan(halfAngle)

            let prevDir = toPrev / prevLen
            let nextDir = toNext / nextLen
            let tangentA = curr + prevDir * offset
            let tangentB = curr + nextDir * offset

            if i == 0 { path.move(to: tangentA) } else { path.line(to: tangentA) }

            if smooth <= 0 {
                let bisector = prevDir + nextDir
                let bisectorLen = bisector.length
                if bisectorLen > 0 {
                    let bisectorNorm = bisector / bisectorLen
                    let centerDist = effectiveRadius / sin(halfAngle)
                    let sign: Double = concave ? -1 : 1
                    let center = curr + bisectorNorm * centerDist * sign
                    let startAngle = atan2(tangentA.y - center.y, tangentA.x - center.x)
                    let endAngle = atan2(tangentB.y - center.y, tangentB.x - center.x)
                    path.arc(center: center, radius: effectiveRadius, startAngle: startAngle, endAngle: endAngle, clockwise: !concave)
                }
            } else {
                let k = 0.552 + smooth * 0.25
                let cpA = tangentA.lerp(to: curr, t: k)
                let cpB = tangentB.lerp(to: curr, t: k)
                path.curve(to: tangentB, control1: cpA, control2: cpB)
            }
        }

        path.close()
        return path
    }

    static func chamferVertices(_ vertices: [Point], size: Double) -> Path {
        let n = vertices.count
        var path = Path()

        for i in 0..<n {
            let prev = vertices[(i - 1 + n) % n]
            let curr = vertices[i]
            let next = vertices[(i + 1) % n]

            let toPrev = prev - curr
            let toNext = next - curr
            let prevLen = toPrev.length
            let nextLen = toNext.length

            guard prevLen > 0, nextLen > 0 else { continue }

            let offset = min(size, min(prevLen, nextLen) * 0.45)
            let tangentA = curr + (toPrev / prevLen) * offset
            let tangentB = curr + (toNext / nextLen) * offset

            if i == 0 { path.move(to: tangentA) } else { path.line(to: tangentA) }
            path.line(to: tangentB)
        }

        path.close()
        return path
    }
}
